/**
 * Autonomous Telegram Channel Manager - Researcher Agent
 *
 * Phase 8: Autonomous Research Intelligence
 * Performs real Gemini-powered research, discovery, and synthesis.
 * Editorial Niche: AI + technology + automation
 * Editorial Philosophy: "Technology that matters, explained and made useful."
 */

import { IGeminiService } from '../ai/gemini.ts';
import { AgentExecutionResult, AgentMetadata, BaseEvent, IAgent, ResearchRequestedPayload } from '../types/index.ts';
import { Logger } from '../utils/logger.ts';

const logger = new Logger('Agent:Researcher');

export interface ResearchOutput {
  id: string;
  topic: string;
  summary: string;
  keyTakeaways: string[];
  suggestedSources: string[];
  relevanceScore: number;
  category?: string;
  deduplicated?: boolean;
}

interface CachedResearchEntry {
  normalizedTopic: string;
  output: ResearchOutput;
  timestamp: number;
}

export class ResearcherAgent implements IAgent<ResearchRequestedPayload, ResearchOutput> {
  public readonly metadata: AgentMetadata = {
    name: 'ResearcherAgent',
    role: 'researcher',
    version: '0.2.0-autonomous-intelligence',
    description: 'Autonomous AI research agent that discovers, validates, and synthesizes high-signal tech developments via Gemini.',
    isAutonomous: true,
    status: 'ready',
  };

  private recentResearchCache: CachedResearchEntry[] = [];
  private deduplicationWindowMs: number;

  constructor(
    private geminiService?: IGeminiService,
    deduplicationWindowMs = 30 * 60 * 1000 // 30-minute deduplication window
  ) {
    this.deduplicationWindowMs = deduplicationWindowMs;
  }

  public canHandle(event: BaseEvent): boolean {
    return event.type === 'research.requested';
  }

  private normalizeTopic(topic: string): string {
    return topic.toLowerCase().replace(/[^a-z0-9]/g, '').trim();
  }

  private findCachedEntry(topic?: string): CachedResearchEntry | undefined {
    if (!topic || !topic.trim()) return undefined;
    const normalized = this.normalizeTopic(topic);
    const now = Date.now();

    // Clean expired entries
    this.recentResearchCache = this.recentResearchCache.filter(
      (entry) => now - entry.timestamp < this.deduplicationWindowMs
    );

    return this.recentResearchCache.find((entry) => entry.normalizedTopic === normalized);
  }

  private recordCacheEntry(output: ResearchOutput): void {
    const normalized = this.normalizeTopic(output.topic);
    if (!normalized) return;

    this.recentResearchCache.unshift({
      normalizedTopic: normalized,
      output,
      timestamp: Date.now(),
    });

    if (this.recentResearchCache.length > 50) {
      this.recentResearchCache.pop();
    }
  }

  public async execute(
    input: ResearchRequestedPayload,
    correlationId?: string
  ): Promise<AgentExecutionResult<ResearchOutput>> {
    const startTime = Date.now();
    const niche = input.niche || 'AI + technology + automation';
    const requestedTopic = input.topic?.trim();

    logger.info('research_job_started', `Research evaluation initiated: ${requestedTopic || 'Autonomous Tech Discovery'}`, {
      correlationId,
      context: { niche, hasGemini: Boolean(this.geminiService?.isConfigured()) },
    });

    // 1. Deduplication check against recent research cycles
    if (requestedTopic) {
      const cached = this.findCachedEntry(requestedTopic);
      if (cached) {
        logger.info('research_deduplicated', `Returning existing research for topic: "${requestedTopic}"`, {
          correlationId,
          context: { originalId: cached.output.id },
        });

        return {
          success: true,
          data: {
            ...cached.output,
            deduplicated: true,
          },
          durationMs: Date.now() - startTime,
          metadata: {
            deduplicated: true,
            originalId: cached.output.id,
          },
        };
      }
    }

    // 2. Real Gemini-Powered Autonomous Research
    if (this.geminiService && this.geminiService.isConfigured()) {
      try {
        logger.info('gemini_research_invoked', `Invoking Gemini 3.7 Flash for technical research: ${requestedTopic || 'Autonomous Discovery'}`, {
          correlationId,
        });

        const geminiResult = await this.geminiService.performResearch({
          topic: requestedTopic,
          niche,
          sourceHints: input.sourceHints,
          maxItems: input.maxItems,
        });

        const researchOutput: ResearchOutput = {
          id: `res_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
          topic: geminiResult.topic || requestedTopic || 'Emerging AI Architecture',
          summary: geminiResult.summary,
          keyTakeaways:
            geminiResult.keyTakeaways && geminiResult.keyTakeaways.length > 0
              ? geminiResult.keyTakeaways
              : ['Key technical insights generated by autonomous intelligence.'],
          suggestedSources:
            geminiResult.suggestedSources && geminiResult.suggestedSources.length > 0
              ? geminiResult.suggestedSources
              : ['https://arxiv.org', 'https://github.com'],
          relevanceScore:
            typeof geminiResult.relevanceScore === 'number'
              ? Math.max(0, Math.min(1, geminiResult.relevanceScore))
              : 0.9,
          category: geminiResult.category || 'AI & Technology',
        };

        // Cache for deduplication
        this.recordCacheEntry(researchOutput);

        logger.info('gemini_research_completed', `Synthesized research: "${researchOutput.topic}" [Score: ${researchOutput.relevanceScore}]`, {
          correlationId,
          context: { researchId: researchOutput.id, topic: researchOutput.topic },
        });

        return {
          success: true,
          data: researchOutput,
          durationMs: Date.now() - startTime,
          metadata: {
            source: 'gemini',
            model: 'gemini-3.7-flash',
            intelligence: 'autonomous_real',
          },
        };
      } catch (err) {
        logger.warn('gemini_research_failed_fallback', 'Gemini research failed, falling back to structured baseline', {
          correlationId,
          error: err,
        });
      }
    }

    // 3. Fallback baseline when Gemini is not configured or errors
    const fallbackTopic = requestedTopic || 'Edge-Optimized Neural Reranking Architectures';
    const fallbackOutput: ResearchOutput = {
      id: `res_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      topic: fallbackTopic,
      summary:
        `Deep technical analysis of ${fallbackTopic}. ` +
        'Evaluates latency improvements, compute distribution across edge worker isolates, and practical developer integration.',
      keyTakeaways: [
        'Edge compute reduces round-trip inference latency to sub-50ms.',
        'Deterministic state caching improves fault tolerance.',
        'Modular pipeline orchestration simplifies continuous agent workflows.',
      ],
      suggestedSources: input.sourceHints?.length
        ? input.sourceHints
        : ['https://developers.cloudflare.com', 'https://arxiv.org'],
      relevanceScore: 0.88,
      category: 'Edge & Infrastructure',
    };

    this.recordCacheEntry(fallbackOutput);

    return {
      success: true,
      data: fallbackOutput,
      durationMs: Date.now() - startTime,
      metadata: {
        source: 'structured_fallback',
        note: this.geminiService?.isConfigured()
          ? 'Gemini call encountered error; resilient fallback provided.'
          : 'GEMINI_API_KEY is not configured; structured baseline provided.',
      },
    };
  }
}

